### ISSUE TITLE
Issue: Unable to save offline site due to sanitize coroutine not awaited

### ISSUE THREAD

**Issue by devinat1** [janreges/siteone-crawler#17]
```
/home/bond/miniconda3/envs/collector/lib/python3.12/asyncio/events.py:88: RuntimeWarning: coroutine 'sanitize' was never awaited
  self._context.run(self._callback, *self._args)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

This issue occurs on mac and linux.

**Comment by janreges** [comment]
Hi @devinat1, 

Can you please send more information? What specific command you run, with what parameters, and ideally also what URL you are trying to analyze/export.

Python, from which your log comes from, is not used in the project at all, so I'm interested in more context to understand how you run the crawler.

**Comment by devinat1** [comment]
Hi @janreges this is the exact script I use to generate the clones: https://gist.github.com/devinat1/38a3261736e2a4cf5b54af3107b753e0

**Comment by janreges** [comment]
Hi @devinat1,

this problem seems to have nothing to do with the crawler itself, but the error is in your python script.

I'm not a python expert, but at first glance I can see that you have the `sanitize` function declared as `async`, but you don't use `await` when using it.

<img width="620" alt="image" src="https://github.com/user-attachments/assets/fb0542a3-65c3-4441-a414-c03eac8d803c">

**Comment by devinat1** [comment]
Yes that error is mine! Thanks for catching. However, regardless of this error, none of the clones are saved. I will re-run this script to see what the issue is. Closing for now since it is not an issue of siteone-crawler.
