### ISSUE TITLE
Feature request: read xml sitemaps for efficient crawling and hidden pages

### ISSUE THREAD

**Issue by sebastian-fahrenkrog** [janreges/siteone-crawler#25]
It would be super nice to have a possibility to add xml sitemaps as the crawling starting point. 

This would be useful for exporting sites and to be sure that every site is found and exported.

**Comment by janreges** [comment]
Hi @sebastian-fahrenkrog,

the current version of the crawler in the main branch now includes the possibility to pass the URL to sitemap.xml or sitemap index xml as url.

If you know how to use Git, you can try it out. Otherwise, you have to wait for the release of the next version 1.0.9. I will release it in the next 2-3 weeks.

I hope you enjoyed this feature and thank you for the feature request ;-)

**Comment by sebastian-fahrenkrog** [comment]
@janreges Wow, amazing! Thank you so much! Will try it out!
